#ref mac build action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,6 +37,8 @@ jobs:
     strategy:
       matrix:
         arch: [x64, arm64]
+    env:
+      CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -53,13 +55,10 @@ jobs:
       - name: Prepare signing certificate
         env:
           CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
-          CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
         run: |
           echo "$CERTIFICATE" | base64 --decode > certificate.p12
 
       - name: Configure macOS keychain for signing
-        env:
-          CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
         run: |
           security create-keychain -p "" build.keychain
           security default-keychain -s build.keychain
@@ -72,34 +71,25 @@ jobs:
         env:
           ARCH: ${{ matrix.arch }}
           CSC_LINK: certificate.p12
-          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
         run: |
+          echo "Building for architecture: $ARCH"
           yarn run build:mac
 
-      - name: Find the generated .dmg file
-        id: find-dmg
-        run: |
-          dmg_file=$(find dist -name "*.dmg" | head -n 1)
-          if [ -z "$dmg_file" ]; then
-            echo "Error: No .dmg file found in the dist directory."
-            exit 1
-          fi
-          echo "Found .dmg file: $dmg_file"
-          echo "dmg_file=$dmg_file" >> $GITHUB_ENV
-
-      - name: Notarize the macOS app with notarytool
+      - name: Notarize and validate App
         env:
           APPLE_ID: ${{ secrets.APPLE_ID }}
           APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
           TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
-          DMG_FILE: ${{ env.dmg_file }}
         run: |
+          dmg_file=$(find dist -name "*.dmg" | head -n 1)
+          if [ -z "$dmg_file" ]; then
+            echo "Error: No .dmg file found."
+            exit 1
+          fi
           xcrun notarytool store-credentials "AC_PASSWORD" --apple-id "$APPLE_ID" --password "$APPLE_ID_PASSWORD" --team-id "$TEAM_ID"
-          xcrun notarytool submit "$DMG_FILE" --keychain-profile "AC_PASSWORD" --wait
-
-      - name: Staple notarization ticket
-        run: |
-          xcrun stapler staple "${{ env.dmg_file }}"
+          xcrun notarytool submit "$dmg_file" --keychain-profile "AC_PASSWORD" --wait
+          xcrun stapler staple "$dmg_file"
+          spctl -a -vvv -t install "$dmg_file"
 
       - name: Upload macOS artifact
         uses: actions/upload-artifact@v3
